assert(SMODS.load_file("src/jokers.lua"))()
assert(SMODS.load_file("src/atlas.lua"))()
assert(SMODS.load_file("src/booster.lua"))()
assert(SMODS.load_file("src/sets.lua"))()
assert(SMODS.load_file("src/rarity.lua"))()
